### ISSUE TITLE
Discuss Sign-up spam protection

### ISSUE THREAD

**Issue by ctrlc03** [quadratic-funding/mpc-phase2-suite#170]
Firebase feature to discuss for coordinators

On the client side, this might simply need error handling to show a meaningful error message to the users being rate limited. 
On the server side, this is up to the coordinator whether to enforce it or not on their firebase application. 

Documentation has been added to the security guidelines for coordinators.

**Comment by ctrlc03** [comment]
> UP: Any updates on this?

This feature has been documented in the security guidelines, it is up to the coordinator to enforce it on their firebase inf. On our side, we need to test how enabling this affects the application - and possibly add a meaningful message for users if rate limited.

**Comment by 0xjei** [comment]
> 

Okay, I think this discussion part can be closed here. Feel free to open a new issue for keeping track of testing and validation of the idea (+ the message for users when rate limited).

**Comment by 0xjei** [comment]
Okay, I think this discussion part can be closed here. Feel free to open a new issue for keeping track of testing and validation of the idea (+ the message for users when rate limited).
