### ISSUE TITLE
Github Authentication Token Expiration

### ISSUE THREAD

**Issue by ctrlc03** [quadratic-funding/mpc-phase2-suite#171]
Test how this would affect the tool, and document usage for coordinator setup

**Comment by 0xjei** [comment]
UP: Any thoughts on this?

**Comment by ctrlc03** [comment]
> UP: Any thoughts on this?

I think it would be great to test how this affects the application. The expiration can be set when creating the OAuth2 app on GitHub, therefore it will be up to the coordinator to set it or not. Usage has been documented in the security guidelines.

**Comment by 0xjei** [comment]
> > UP: Any thoughts on this?
> 
> I think it would be great to test how this affects the application. The expiration can be set when creating the OAuth2 app on GitHub, therefore it will be up to the coordinator to set it or not. Usage has been documented in the security guidelines.

I think that's an important feature for the first release. Let's hold on for a moment, later when testing is completed we can resume the work on this.

**Comment by 0xjei** [comment]
"GitHub will automatically revoke an OAuth token or personal access token when the token hasn't been used in one year"

There are other few possibilities for token expiration and revocation. Check out the official docs here [Token Expiration and Revocation](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/token-expiration-and-revocation).

We just need to provide a mechanism for getting rid of the token (stored in the local device of the user) and inform the user to repeat the authentication to generate a new one. The Firebase Authentication service will take care to maintain the same UID for the user thus updating the expired token with the new one. 

We can catch when someone is trying to use an expired token whenever they receives an `Unsuccessful check authorization response from Github` error from Firebase.
