### ISSUE TITLE
[E2 - MS1] - Dae

### ISSUE THREAD

**Issue by 0xjei** [quadratic-funding/mpc-phase2-suite#183]
Post your solution in the comments 😄 

ps. remember to assign the amount of story points in the dedicated label.

**Comment by gurrpi** [comment]
https://gist.githubusercontent.com/gurrpi/6be1e6db3a29e92b08dc2ab20aefddc8/raw/65834c408700d4e84cbc74ac6c3344e04c089bd1/main.circom
