### ISSUE TITLE
[E2 - MS2] - Dae

### ISSUE THREAD

**Issue by 0xjei** [quadratic-funding/mpc-phase2-suite#186]
Post your solution in the comments 😄 (private repo and invite Q and others when needed).

ps. remember to assign the amount of story points in the dedicated label.

**Comment by gurrpi** [comment]
* https://github.com/gurrpi/mpc-phase2-suite/commit/e250a3b8ea19f3367d251440c85de4811028d18b
* https://github.com/gurrpi/mpc-phase2-suite/commit/55c7c7f714c917ff7ea6d89a331c269c38730a90
