### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by gurrpi** [quadratic-funding/mpc-phase2-suite#189]
There is a room for improvement for error message format to help user to identify a cause of error. For example, printing a stack trace would help where does an error happened exactly.

Currently, we uses following message format generally:
```
logMsg(`Something went wrong: ${error.toString()}`, MsgType.ERROR)
```

**Comment by gurrpi** [comment]
[This article](https://wix-ux.com/when-life-gives-you-lemons-write-better-error-messages-46c5223e1a2f) might be helpful to compose clear message.

Following is the extracts from above article:

* What makes a bad error message
![FfXAIehXwAENTbA](https://user-images.githubusercontent.com/1610146/201493563-5379e0fc-a340-42cc-a169-56f530148164.jpeg)

* What makes a good error message:
![FfXAImdXEAEbGrJ](https://user-images.githubusercontent.com/1610146/201493569-a51af239-905c-48b0-b80c-c2f1945f9efd.jpeg)

**Comment by 0xjei** [comment]
I read the article, an interesting point of view. My takeaways:
- We should definitely revise the errors. They were made in a way to track them but not from a user perspective (especially, the generic ones).
- Add a Troubleshooting FAQ section in the Wiki. What do you think?

**Comment by 0xjei** [comment]
Goal achieved during the last refactoring
