### ISSUE TITLE
Set up a github action that triggers MPC tool CLI

### ISSUE THREAD

**Issue by daodesigner** [quadratic-funding/mpc-phase2-suite#197]
You should create a circom repo with the circuits and tests that you wrote for HW 2. Ask @gurrpi for help if you get stuck, but you should all understand how this works.

On pull request to main branch being merged:

trigger the mpcphase2suite CLI
bonus points: start a ceremony for the circuit

**Comment by 0xjei** [comment]
TL;DR I published a version of the CLI with the configuration for our test environment infra (@jeeiii/phase2cli - v0.0.5). Then, I created 2 workflows: one for triggering the CLI (simply shows the version) and a second one which runs the HW2-related tests.

Also, I have moved the .r1cs files in a single folder after compilation and run npx phase2cli auth and npx phase2cli coordinate setup then.

PR: https://github.com/0xjei/circom-starter/pull/2
Log: https://www.notion.so/pse-team/Epic-2-Eat-the-Dogfood-b2b0aa54119d4b22acea6d4f820a4a89#c5c46ddaff02481eb6bb7b2e8d7c22f4
