### ISSUE TITLE
Wrong variable name / comment

### ISSUE THREAD

**Issue by ctrlc03** [quadratic-funding/mpc-phase2-suite#273]
* [ ] - Change [publicOutputs](https://github.com/quadratic-funding/mpc-phase2-suite/blob/dev/packages/phase2cli/src/commands/setup.ts#L289) to `publicInputs`
* [ ] - Change [comment](https://github.com/quadratic-funding/mpc-phase2-suite/blob/dev/packages/phase2cli/src/commands/finalize.ts#L165
) to `// upload Solidity verifier to storage.`
* [ ] - Change [comment](https://github.com/quadratic-funding/mpc-phase2-suite/blob/dev/packages/phase2cli/src/commands/finalize.ts#L190) to `// Finalize ceremony on the server`

**Comment by 0xjei** [comment]
Good catch. I will change this while working on the refactoring of `setup` command this week!

**Comment by daodesigner** [comment]
Let's focus on the critical path here
