### ISSUE TITLE
Could't resolve a package.json when running globally installed cli

### ISSUE THREAD

**Issue by gurrpi** [quadratic-funding/mpc-phase2-suite#45]
This [code](https://github.com/quadratic-funding/mpc-phase2-suite/blob/dev/cli/src/lib/auth.ts#L19) try to find the `package.json` file from current working directory where cli command has been called. So it only success only if cli command called from specific directory(e.g. `/Users/daehyun/test/node_modules/@gurrpi/mpc-phase2-suite-cli/dist/` in following example).

```
file:///Users/daehyun/test/node_modules/@gurrpi/mpc-phase2-suite-cli/dist/src/lib/files.js:104
        throw new Error("Oops, looks like that the provided file path does not exist!");
              ^

Error: Oops, looks like that the provided file path does not exist!
    at readJSONFile (file:///Users/daehyun/test/node_modules/@gurrpi/mpc-phase2-suite-cli/dist/src/lib/files.js:104:15)
    at file:///Users/daehyun/test/node_modules/@gurrpi/mpc-phase2-suite-cli/dist/src/lib/auth.js:46:11
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
```

## Reproduce

```
mkdir tempDir
cd tempDir

npm i @gurrpi/mpc-phase2-suite-cli@0.0.3
npx phase2cli
```

**Comment by 0xjei** [comment]
Mmh I didn't get the same error following the steps for reproducing it above. However, I got it when I try to run the phase2cli from a different directory (e.g., your steps + cd node_modules/ + npx phase2cli).
